### ISSUE TITLE
Does not work under qemu-gdb

### ISSUE THREAD

**Issue by Zhou-Heng** [zhxq/xv6windows#1]
If run make qemu-gdb (or make qemu-nox-gdb) in WSL, qemu and gdb will freeze.
Do you know how to fix it? Microsoft refuses to admit this bug.

**Comment by zhxq** [comment]
I don't know if you are using WSL 1 or WSL 2. This was written when WSL 2 does not exist at all, but many users are using WSL 2. 

If you are using WSL 2, I suggest you to enable nested virtualization with a newer Linux kernel - I compiled my own kernel for that, but I did not test qemu-gdb yet.

If you are using WSL 1, tell me and I will see if I can run it.

**Comment by Zhou-Heng** [comment]
Hi, zhxq:

Thank you for the reply. I had thought gdb can be launched automatically and pause at the first instruction like Visual Studio, but later I realized that gdb is supposed to be running separately from qemu+xv6 and to connect to qemu+xv6 to start debugging. I did not know that when submitting the ticket and thought it is the problem of WSL (there is no problem when working with qemu+xv6 with WSL 1 so far), so I asked here. Now the problem has been solved, please close this ticket. Thank you and have a good evening.

**Comment by zhxq** [comment]
No problem! I am happy to see my tutorial can help as many people as it could. Have a great day!

zhxq
